name: "Windows Standalone Build"

on:
  push:
    tags: "v[0-9]+.[0-9]+.[0-9]+"
    branches: winbuild2

jobs:

  build:

    name: "Build Windows standalone version"
    runs-on: windows-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: "Install MSYS2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: git mingw-w64-x86_64-toolchain

      # Build GTK

      - name: "Build GTK"
        shell: cmd
        run: |
          winbuild\build-gtk.bat

      - name: "Upload GTK build artifact"
        uses: actions/upload-artifact@v2
        with:
          name: gtk-build
          path: gtk-build\gtk\x64\release\

      # Build YOGA Image Optimizer

      - name: "Build YOGA Image Optimizer"
        shell: cmd
        run: |
          winbuild\build-yoga.bat

      - name: "Add Windows 10 GTK Theme"
        shell: cmd
        run: |
          winbuild\add-gtk-theme.bat

      - name: "Clean the GTK build"
        shell: bash
        run: |
          winbuild/clean-gtk.sh

      # Zip distribution

      - name: "Build the Windows Zip distribution"
        shell: cmd
        run: |
          winbuild\build-zip.bat

      - name: "Upload the Windows Zip artifact"
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.zip

      # Windows installer

      - name: "Build the Windows Installer distribution (InnoSetup)"
        shell: cmd
        run: |
          winbuild\build-installer.bat

      - name: "Upload the Windows Installer artifact"
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.exe

